apiVersion: v1
kind: Service
metadata:
  name: concert-service-svc
  namespace: microservices
spec:
  selector:
    app: concert-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
